/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RootPathsRouteImport } from './routes/root-paths'
import { Route as RepositoryRouteImport } from './routes/repository'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RepositoryIdRouteRouteImport } from './routes/repository.$id/route'
import { Route as RepositoryIdIndexRouteImport } from './routes/repository.$id/index'
import { Route as RepositoryIdPullsRouteImport } from './routes/repository.$id/pulls'
import { Route as RepositoryIdInsightsRouteImport } from './routes/repository.$id/insights'
import { Route as RepositoryIdFilesRouteImport } from './routes/repository.$id/files'
import { Route as RepositoryIdCommitsRouteRouteImport } from './routes/repository.$id/commits/route'
import { Route as RepositoryIdDiffHashRouteImport } from './routes/repository.$id/diff.$hash'
import { Route as RepositoryIdCommitsBranchRouteImport } from './routes/repository.$id/commits/$branch'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RootPathsRoute = RootPathsRouteImport.update({
  id: '/root-paths',
  path: '/root-paths',
  getParentRoute: () => rootRouteImport,
} as any)
const RepositoryRoute = RepositoryRouteImport.update({
  id: '/repository',
  path: '/repository',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RepositoryIdRouteRoute = RepositoryIdRouteRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => RepositoryRoute,
} as any)
const RepositoryIdIndexRoute = RepositoryIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RepositoryIdRouteRoute,
} as any)
const RepositoryIdPullsRoute = RepositoryIdPullsRouteImport.update({
  id: '/pulls',
  path: '/pulls',
  getParentRoute: () => RepositoryIdRouteRoute,
} as any)
const RepositoryIdInsightsRoute = RepositoryIdInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => RepositoryIdRouteRoute,
} as any)
const RepositoryIdFilesRoute = RepositoryIdFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => RepositoryIdRouteRoute,
} as any)
const RepositoryIdCommitsRouteRoute =
  RepositoryIdCommitsRouteRouteImport.update({
    id: '/commits',
    path: '/commits',
    getParentRoute: () => RepositoryIdRouteRoute,
  } as any)
const RepositoryIdDiffHashRoute = RepositoryIdDiffHashRouteImport.update({
  id: '/diff/$hash',
  path: '/diff/$hash',
  getParentRoute: () => RepositoryIdRouteRoute,
} as any)
const RepositoryIdCommitsBranchRoute =
  RepositoryIdCommitsBranchRouteImport.update({
    id: '/$branch',
    path: '/$branch',
    getParentRoute: () => RepositoryIdCommitsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/repository': typeof RepositoryRouteWithChildren
  '/root-paths': typeof RootPathsRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/repository/$id': typeof RepositoryIdRouteRouteWithChildren
  '/repository/$id/commits': typeof RepositoryIdCommitsRouteRouteWithChildren
  '/repository/$id/files': typeof RepositoryIdFilesRoute
  '/repository/$id/insights': typeof RepositoryIdInsightsRoute
  '/repository/$id/pulls': typeof RepositoryIdPullsRoute
  '/repository/$id/': typeof RepositoryIdIndexRoute
  '/repository/$id/commits/$branch': typeof RepositoryIdCommitsBranchRoute
  '/repository/$id/diff/$hash': typeof RepositoryIdDiffHashRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/repository': typeof RepositoryRouteWithChildren
  '/root-paths': typeof RootPathsRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/repository/$id/commits': typeof RepositoryIdCommitsRouteRouteWithChildren
  '/repository/$id/files': typeof RepositoryIdFilesRoute
  '/repository/$id/insights': typeof RepositoryIdInsightsRoute
  '/repository/$id/pulls': typeof RepositoryIdPullsRoute
  '/repository/$id': typeof RepositoryIdIndexRoute
  '/repository/$id/commits/$branch': typeof RepositoryIdCommitsBranchRoute
  '/repository/$id/diff/$hash': typeof RepositoryIdDiffHashRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/repository': typeof RepositoryRouteWithChildren
  '/root-paths': typeof RootPathsRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/repository/$id': typeof RepositoryIdRouteRouteWithChildren
  '/repository/$id/commits': typeof RepositoryIdCommitsRouteRouteWithChildren
  '/repository/$id/files': typeof RepositoryIdFilesRoute
  '/repository/$id/insights': typeof RepositoryIdInsightsRoute
  '/repository/$id/pulls': typeof RepositoryIdPullsRoute
  '/repository/$id/': typeof RepositoryIdIndexRoute
  '/repository/$id/commits/$branch': typeof RepositoryIdCommitsBranchRoute
  '/repository/$id/diff/$hash': typeof RepositoryIdDiffHashRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/repository'
    | '/root-paths'
    | '/search'
    | '/settings'
    | '/repository/$id'
    | '/repository/$id/commits'
    | '/repository/$id/files'
    | '/repository/$id/insights'
    | '/repository/$id/pulls'
    | '/repository/$id/'
    | '/repository/$id/commits/$branch'
    | '/repository/$id/diff/$hash'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/repository'
    | '/root-paths'
    | '/search'
    | '/settings'
    | '/repository/$id/commits'
    | '/repository/$id/files'
    | '/repository/$id/insights'
    | '/repository/$id/pulls'
    | '/repository/$id'
    | '/repository/$id/commits/$branch'
    | '/repository/$id/diff/$hash'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/repository'
    | '/root-paths'
    | '/search'
    | '/settings'
    | '/repository/$id'
    | '/repository/$id/commits'
    | '/repository/$id/files'
    | '/repository/$id/insights'
    | '/repository/$id/pulls'
    | '/repository/$id/'
    | '/repository/$id/commits/$branch'
    | '/repository/$id/diff/$hash'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  RepositoryRoute: typeof RepositoryRouteWithChildren
  RootPathsRoute: typeof RootPathsRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/root-paths': {
      id: '/root-paths'
      path: '/root-paths'
      fullPath: '/root-paths'
      preLoaderRoute: typeof RootPathsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repository': {
      id: '/repository'
      path: '/repository'
      fullPath: '/repository'
      preLoaderRoute: typeof RepositoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repository/$id': {
      id: '/repository/$id'
      path: '/$id'
      fullPath: '/repository/$id'
      preLoaderRoute: typeof RepositoryIdRouteRouteImport
      parentRoute: typeof RepositoryRoute
    }
    '/repository/$id/': {
      id: '/repository/$id/'
      path: '/'
      fullPath: '/repository/$id/'
      preLoaderRoute: typeof RepositoryIdIndexRouteImport
      parentRoute: typeof RepositoryIdRouteRoute
    }
    '/repository/$id/pulls': {
      id: '/repository/$id/pulls'
      path: '/pulls'
      fullPath: '/repository/$id/pulls'
      preLoaderRoute: typeof RepositoryIdPullsRouteImport
      parentRoute: typeof RepositoryIdRouteRoute
    }
    '/repository/$id/insights': {
      id: '/repository/$id/insights'
      path: '/insights'
      fullPath: '/repository/$id/insights'
      preLoaderRoute: typeof RepositoryIdInsightsRouteImport
      parentRoute: typeof RepositoryIdRouteRoute
    }
    '/repository/$id/files': {
      id: '/repository/$id/files'
      path: '/files'
      fullPath: '/repository/$id/files'
      preLoaderRoute: typeof RepositoryIdFilesRouteImport
      parentRoute: typeof RepositoryIdRouteRoute
    }
    '/repository/$id/commits': {
      id: '/repository/$id/commits'
      path: '/commits'
      fullPath: '/repository/$id/commits'
      preLoaderRoute: typeof RepositoryIdCommitsRouteRouteImport
      parentRoute: typeof RepositoryIdRouteRoute
    }
    '/repository/$id/diff/$hash': {
      id: '/repository/$id/diff/$hash'
      path: '/diff/$hash'
      fullPath: '/repository/$id/diff/$hash'
      preLoaderRoute: typeof RepositoryIdDiffHashRouteImport
      parentRoute: typeof RepositoryIdRouteRoute
    }
    '/repository/$id/commits/$branch': {
      id: '/repository/$id/commits/$branch'
      path: '/$branch'
      fullPath: '/repository/$id/commits/$branch'
      preLoaderRoute: typeof RepositoryIdCommitsBranchRouteImport
      parentRoute: typeof RepositoryIdCommitsRouteRoute
    }
  }
}

interface RepositoryIdCommitsRouteRouteChildren {
  RepositoryIdCommitsBranchRoute: typeof RepositoryIdCommitsBranchRoute
}

const RepositoryIdCommitsRouteRouteChildren: RepositoryIdCommitsRouteRouteChildren =
  {
    RepositoryIdCommitsBranchRoute: RepositoryIdCommitsBranchRoute,
  }

const RepositoryIdCommitsRouteRouteWithChildren =
  RepositoryIdCommitsRouteRoute._addFileChildren(
    RepositoryIdCommitsRouteRouteChildren,
  )

interface RepositoryIdRouteRouteChildren {
  RepositoryIdCommitsRouteRoute: typeof RepositoryIdCommitsRouteRouteWithChildren
  RepositoryIdFilesRoute: typeof RepositoryIdFilesRoute
  RepositoryIdInsightsRoute: typeof RepositoryIdInsightsRoute
  RepositoryIdPullsRoute: typeof RepositoryIdPullsRoute
  RepositoryIdIndexRoute: typeof RepositoryIdIndexRoute
  RepositoryIdDiffHashRoute: typeof RepositoryIdDiffHashRoute
}

const RepositoryIdRouteRouteChildren: RepositoryIdRouteRouteChildren = {
  RepositoryIdCommitsRouteRoute: RepositoryIdCommitsRouteRouteWithChildren,
  RepositoryIdFilesRoute: RepositoryIdFilesRoute,
  RepositoryIdInsightsRoute: RepositoryIdInsightsRoute,
  RepositoryIdPullsRoute: RepositoryIdPullsRoute,
  RepositoryIdIndexRoute: RepositoryIdIndexRoute,
  RepositoryIdDiffHashRoute: RepositoryIdDiffHashRoute,
}

const RepositoryIdRouteRouteWithChildren =
  RepositoryIdRouteRoute._addFileChildren(RepositoryIdRouteRouteChildren)

interface RepositoryRouteChildren {
  RepositoryIdRouteRoute: typeof RepositoryIdRouteRouteWithChildren
}

const RepositoryRouteChildren: RepositoryRouteChildren = {
  RepositoryIdRouteRoute: RepositoryIdRouteRouteWithChildren,
}

const RepositoryRouteWithChildren = RepositoryRoute._addFileChildren(
  RepositoryRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  RepositoryRoute: RepositoryRouteWithChildren,
  RootPathsRoute: RootPathsRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
