/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RepositoryRouteImport } from './routes/repository'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RepositoryIdRouteImport } from './routes/repository.$id'

const RepositoryRoute = RepositoryRouteImport.update({
  id: '/repository',
  path: '/repository',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RepositoryIdRoute = RepositoryIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => RepositoryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/repository': typeof RepositoryRouteWithChildren
  '/repository/$id': typeof RepositoryIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/repository': typeof RepositoryRouteWithChildren
  '/repository/$id': typeof RepositoryIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/repository': typeof RepositoryRouteWithChildren
  '/repository/$id': typeof RepositoryIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/repository' | '/repository/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/repository' | '/repository/$id'
  id: '__root__' | '/' | '/repository' | '/repository/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RepositoryRoute: typeof RepositoryRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/repository': {
      id: '/repository'
      path: '/repository'
      fullPath: '/repository'
      preLoaderRoute: typeof RepositoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repository/$id': {
      id: '/repository/$id'
      path: '/$id'
      fullPath: '/repository/$id'
      preLoaderRoute: typeof RepositoryIdRouteImport
      parentRoute: typeof RepositoryRoute
    }
  }
}

interface RepositoryRouteChildren {
  RepositoryIdRoute: typeof RepositoryIdRoute
}

const RepositoryRouteChildren: RepositoryRouteChildren = {
  RepositoryIdRoute: RepositoryIdRoute,
}

const RepositoryRouteWithChildren = RepositoryRoute._addFileChildren(
  RepositoryRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RepositoryRoute: RepositoryRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
